### ISSUE TITLE
Other requirements

### ISSUE THREAD

**Issue by ihsancan-w** [nobu-g/cohesion-analysis#2]
Hi, awesome research.
Much appreciated if you could provide torch, cuda, and other library versions.

**Comment by nobu-g** [comment]
Hi, thank you for your comments!
Please refer to [pyproject.toml](https://github.com/nobu-g/cohesion-analysis/blob/main/pyproject.toml) for other requirements.
As for CUDA, any version is fine as long as torch supports it.

**Comment by ihsancan-w** [comment]
Thank you very much. I want to confirm hardware requirements as well.
How much GPU memory we need for inference?

**Comment by nobu-g** [comment]
I think 12GB is enough, but not confirmed...
