### ISSUE TITLE
The deployment of the model

### ISSUE THREAD

**Issue by LostArrows27** [nobu-g/cohesion-analysis#3]
Hi Nobu, i just read your paper about Cohesion Analysis Model and really want to try out the demo of it on demo websit link. But the server just recently down and i can't access to it, can you check the demo link again. Thanks man

**Comment by nobu-g** [comment]
Thank you for reporting the issue!
I've fixed the demo link, so please try again.

**Comment by LostArrows27** [comment]
> Thank you for reporting the issue! I've fixed the demo link, so please try again.

Thanks man,  I'm currently working on an exercise to summary your paper work so the demo would really help

**Comment by nobu-g** [comment]
Actually, the demo backend is now a bit diverged from the paper. Please contact me if you want to reproduce the result of the demo.
